apiVersion: batch/v1
kind: Job
metadata:
  name: glance-post
spec:
  template:
    metadata:
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "init",
            "image": "quay.io/stackanetes/kubernetes-entrypoint:v0.1.0",
            "imagePullPolicy": "{{ .Values.images.pull_policy }}",
            "env": [
              {
                "name": "NAMESPACE",
                "value": "{{ .Release.Namespace }}"
              },            
              {
                "name": "DEPENDENCY_SERVICE",
                "value": "{{  include "joinListWithColon" .Values.dependencies.post.service }}"
              },
              {
                "name": "DEPENDENCY_JOBS",
                "value": "{{  include "joinListWithColon" .Values.dependencies.post.jobs }}"
              },
              {
                "name": "COMMAND",
                "value": "echo done"
              }
            ]
          }
        ]'
    spec:
      nodeSelector:
        {{ .Values.labels.node_selector_key }}: {{ .Values.labels.node_selector_value }}
      restartPolicy: OnFailure
      containers:
        - name: glance-post
          image: {{ .Values.images.post }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
          command:
            - bash
            - /tmp/post.sh
          volumeMounts:
            - name: postsh
              mountPath: /tmp/post.sh
              subPath: post.sh
          env:
          - name: ANSIBLE_LIBRARY
            value: /usr/share/ansible/
          resources:
            requests:
              memory: {{ .Values.resources.glance_post.requests.memory | quote }}
              cpu: {{ .Values.resources.glance_post.requests.cpu | quote }}
            limits:
              memory: {{ .Values.resources.glance_post.limits.memory | quote }}
              cpu: {{ .Values.resources.glance_post.limits.cpu | quote }}
      volumes:
        - name: postsh
          configMap:
            name: glance-postsh

