apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: glance-registry
spec:
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: glance-registry
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "init",
            "image": "quay.io/stackanetes/kubernetes-entrypoint:v0.1.0",
            "imagePullPolicy": "{{ .Values.images.pull_policy }}",
            "env": [
              {
                "name": "NAMESPACE",
                "value": "{{ .Release.Namespace }}"
              },
              {
                "name": "DEPENDENCY_SERVICE",
                "value": "{{  include "joinListWithColon" .Values.dependencies.registry.service }}"
              },
              {
                "name": "DEPENDENCY_JOBS",
                "value": "{{  include "joinListWithColon" .Values.dependencies.registry.jobs }}"
              },
              {
                "name": "COMMAND",
                "value": "echo done"
              }
            ]
          }
        ]'
    spec:
      nodeSelector:
        {{ .Values.labels.node_selector_key }}: {{ .Values.labels.node_selector_value }}
      containers:
        - name: glance-registry
          image: {{ .Values.images.registry }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
          command:
          - glance-registry
          ports:
            - containerPort: {{ .Values.network.port.registry }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.network.port.registry }}
          volumeMounts:
            - name: glanceregistryconf
              mountPath: /etc/glance/glance-registry.conf
              subPath: glance-registry.conf
          resources:
            requests:
              memory: {{ .Values.resources.glance_registry.requests.memory | quote }}
              cpu: {{ .Values.resources.glance_registry.requests.cpu | quote }}
            limits:
              memory: {{ .Values.resources.glance_registry.limits.memory | quote }}
              cpu: {{ .Values.resources.glance_registry.limits.cpu | quote }}
      volumes:
        - name: glanceregistryconf
          configMap:
            name: glance-glanceregistryconf
