{{- $envAll := . }}
{{- $dependencies := .Values.dependencies.api }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ironic-api   
  labels:
    system: openstack
    type: api
    component: ironic
  
spec:
  replicas: {{ .Values.replicas.api }}
  revisionHistoryLimit: {{ .Values.upgrades.revision_history }}
  strategy:
    type: {{ .Values.upgrades.pod_replacement_strategy }}
    {{ if eq .Values.upgrades.pod_replacement_strategy "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.upgrades.rolling_update.max_unavailable }}
      maxSurge: {{ .Values.upgrades.rolling_update.max_surge }}
    {{ end }}
  selector:
    matchLabels:
      name: ironic-api    
  template:
    metadata:
      labels:
        name: ironic-api
      annotations:
        configmap-bin-hash: {{ tuple "configmap-bin.yaml" . | include "helm-toolkit.hash" }}
        configmap-etc-hash: {{ tuple "configmap-etc.yaml" . | include "helm-toolkit.hash" }}
        pod.beta.kubernetes.io/init-containers: '[
{{ tuple $envAll $dependencies | include "helm-toolkit.kubernetes_entrypoint_init_container" | indent 10 }}
        ]'
    spec:
      nodeSelector:
        {{ .Values.labels.control_node_selector_key }}: {{ .Values.labels.control_node_selector_value }}
      containers:
        - name: ironic-api
          image: {{ .Values.images.api }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
          {{- if .Values.resources.enabled }}
          resources:
            requests:
              memory: {{ .Values.resources.ironic_api.requests.memory | quote }}
              cpu: {{ .Values.resources.ironic_api.requests.cpu | quote }}
            limits:
              memory: {{ .Values.resources.ironic_api.limits.memory | quote }}
              cpu: {{ .Values.resources.ironic_api.limits.cpu | quote }}
          {{- end }}
          securityContext:
            privileged: true
          command:
            - bash
            - /container.init/ironic-api-start
          ports:
            - name: ironic-api
              containerPort: {{.Values.ironic.api_port_internal}}
          livenessProbe:
            httpGet:
              path: /
              port: {{.Values.ironic.api_port_internal}}
            initialDelaySeconds: 15
            timeoutSeconds: 5
          volumeMounts:
            - mountPath: /ironic-etc
              name: ironic-etc
            - mountPath: /ironic-patches
              name: ironic-patches
            - mountPath: /container.init
              name: container-init
      volumes:
        - name: ironic-etc
          configMap:
            name: ironic-etc
        - name: ironic-patches
          configMap:
            name: ironic-patches
        - name: container-init
          configMap:
            name: ironic-bin
