apiVersion: v1
kind: ConfigMap
metadata:
  name: ironic-bin
data:
  ironic-api-start: |
{{ .Files.Get "bin/ironic-api-start" | indent 4 }}
  ironic-conductor-start: |
{{ .Files.Get "bin/ironic-conductor-start" | indent 4 }}
  ironic-inspector-start: |
{{ .Files.Get "bin/ironic-inspector-start" | indent 4 }}
  ironic-pxe-start: |
{{ .Files.Get "bin/ironic-pxe-start" | indent 4 }}
  db-migrate-api: |
{{ .Files.Get "bin/db-migrate-api" | indent 4 }}
  db-migrate-inspector: |
{{ .Files.Get "bin/db-migrate-inspector" | indent 4 }}

  common.sh: |
{{ include "common.sh" . | indent 4 }}


