apiVersion: v1
kind: ConfigMap
metadata:
  name: db-maintain-ironic
  labels:
    system: openstack
    type: configuration
    component: database

data:
  db-maintain.sh: |
    #!/usr/bin/env bash

    data_dir=/postgresql-data/data

    cp /postgresql-conf/postgresql.conf  $data_dir/postgresql.conf
    cp /postgresql-conf/pg-hba.conf  $data_dir/pg_hba.conf

    export PGUSER=postgres
    psql <<- EOSQL

        ALTER ROLE {{.Values.postgres.db_user}} WITH ENCRYPTED PASSWORD '{{.Values.postgres.db_password}}';
        ALTER ROLE {{.Values.postgres.inspector_db_user}} WITH ENCRYPTED PASSWORD '{{.Values.postgres.inspector_db_password}}';
        ALTER ROLE {{.Values.postgres.user}} WITH ENCRYPTED PASSWORD '{{.Values.postgres.password}}';

    EOSQL



