kind: Service
apiVersion: v1

metadata:
  name: ironic-inspector
  labels:
    system: openstack
    type: inspector
    component: ironic
spec:
  selector:
    name: ironic-inspector
  ports:
    - name: ironic-inspector
      port: {{.Values.ironic.inspector_port_internal}}
