apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ironic-pxe
  labels:
    system: openstack
    type: backend
    component: ironic
spec:
  replicas: {{ .Values.replicas.pxe }}
  revisionHistoryLimit: {{ .Values.upgrades.revision_history }}
  strategy:
    type: {{ .Values.upgrades.pod_replacement_strategy }}
    {{ if eq .Values.upgrades.pod_replacement_strategy "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.upgrades.rolling_update.max_unavailable }}
      maxSurge: {{ .Values.upgrades.rolling_update.max_surge }}
    {{ end }}
  selector:
    matchLabels:
      name: ironic-pxe
  template:
    metadata:
      labels:
        name: ironic-pxe
      annotations:
        configmap-bin-hash: {{ tuple "configmap-bin.yaml" . | include "helm-toolkit.hash" }}
        configmap-etc-hash: {{ tuple "configmap-etc.yaml" . | include "helm-toolkit.hash" }}
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"species","value":"none"}]'
    spec:
      nodeSelector:
        {{ .Values.labels.control_node_selector_key }}: {{ .Values.labels.control_node_selector_value }}
      hostNetwork: true
      hostPID: true
      hostIPC: true

      containers:
        - name: ironic-pxe
          image: {{ .Values.images.pxe }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
          {{- if .Values.resources.enabled }}
          resources:
            requests:
              memory: {{ .Values.resources.ironic_pxe.requests.memory | quote }}
              cpu: {{ .Values.resources.ironic_pxe.requests.cpu | quote }}
            limits:
              memory: {{ .Values.resources.ironic_pxe.limits.memory | quote }}
              cpu: {{ .Values.resources.ironic_pxe.limits.cpu | quote }}
          {{- end }}
          securityContext:
            privileged: true
          command:
            - bash
            - /container.init/ironic-pxe-start
          ports:
            - name: ironic-pxe
              protocol: UDP
              containerPort: {{ .Values.ironic.pxe_port_public }}
          volumeMounts:
            - mountPath: /ironic-etc
              name: ironic-etc
            - mountPath: /container.init
              name: container-init
      volumes:
        - name: ironic-etc
          configMap:
            name: ironic-etc
        - name: container-init
          configMap:
            name: ironic-bin
