apiVersion: batch/v1
kind: Job
metadata:
  name: heat-db-init
spec:
  template:
    metadata:
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "init",
            "image": {{ .Values.images.dep_check | quote }},
            "imagePullPolicy": {{ .Values.images.pull_policy | quote }},
            "env": [
              {
                "name": "NAMESPACE",
                "value": "{{ .Release.Namespace }}"
              },
              {
                "name": "DEPENDENCY_SERVICE",
                "value": "{{  include "joinListWithColon" .Values.dependencies.db_init.service }}"
              },
              {
                "name": "DEPENDENCY_JOBS",
                "value": "{{  include "joinListWithColon" .Values.dependencies.db_init.jobs }}"
              },
              {
                "name": "COMMAND",
                "value": "echo done"
              }
            ]
          }
        ]'
    spec:
      restartPolicy: OnFailure
      containers:
        - name: heat-db-init
          image: {{ .Values.images.db_init | quote }}
          imagePullPolicy: {{ .Values.images.pull_policy | quote }}
          env:
          - name: ANSIBLE_LIBRARY
            value: /usr/share/ansible/
          command:
            - bash
            - /tmp/db-init.sh
          volumeMounts:
            - name: dbinitsh
              mountPath: /tmp/db-init.sh
              subPath: db-init.sh
              readOnly: true
          resources:
            requests:
              memory: {{ .Values.resources.heat_db_init.requests.memory | quote }}
              cpu: {{ .Values.resources.heat_db_init.requests.cpu | quote }}
            limits:
              memory: {{ .Values.resources.heat_db_init.limits.memory | quote }}
              cpu: {{ .Values.resources.heat_db_init.limits.cpu | quote }}
      volumes:
        - name: dbinitsh
          configMap:
            name: heat-bin
