{{- $envAll := . }}
{{- $ksAdminSecret := .Values.keystone_secrets.admin }}
{{- $dependencies := .Values.dependencies.ks_service }}
apiVersion: batch/v1
kind: Job
metadata:
  name: heat-ks-service
spec:
  template:
    metadata:
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
{{ tuple $envAll $dependencies | include "dep_check_init_cont" | indent 10 }}
        ]'
    spec:
      restartPolicy: OnFailure
      nodeSelector:
        {{ .Values.labels.node_selector_key }}: {{ .Values.labels.node_selector_value }}
      containers:
{{- range $key1, $osServiceName := tuple "heat" "heat-cfn" }}
        - name: {{ $osServiceName }}-ks-service-registration
          image: {{ $envAll.Values.images.ks_service }}
          imagePullPolicy: {{ $envAll.Values.images.pull_policy }}
          {{- if $envAll.Values.resources.enabled }}
          resources:
            requests:
              memory: {{ $envAll.Values.resources.heat_ks_service.requests.memory | quote }}
              cpu: {{ $envAll.Values.resources.heat_ks_service.requests.cpu | quote }}
            limits:
              memory: {{ $envAll.Values.resources.heat_ks_service.limits.memory | quote }}
              cpu: {{ $envAll.Values.resources.heat_ks_service.limits.cpu | quote }}
          {{- end }}
          command:
            - bash
            - /tmp/ks-service.sh
          volumeMounts:
            - name: ks-service-sh
              mountPath: /tmp/ks-service.sh
              subPath: ks-service.sh
              readOnly: true
          env:
{{- with $env := dict "ksUserSecret" $ksAdminSecret }}
{{- include "env_ks_openrc_tpl" $env | indent 12 }}
{{- end }}
            - name: OS_SERVICE_NAME
              value: {{ $osServiceName }}
            - name: OS_SERVICE_TYPE
              value: {{ tuple $osServiceName $envAll | include "endpoint_type_lookup" }}
{{- end }}

      volumes:
        - name: ks-service-sh
          configMap:
            name: heat-bin
