apiVersion: batch/v1
kind: Job
metadata:
  name: keystone-db-sync
spec:
  template:
    metadata:
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "init",
            "image": "{{ .Values.images.entrypoint }}",
            "imagePullPolicy": "{{ .Values.images.pull_policy }}",
            "env": [
              {
                "name": "NAMESPACE",
                "value": "{{ .Release.Namespace }}"
              },            
              {
                "name": "DEPENDENCY_SERVICE",
                "value": "{{  include "joinListWithColon" .Values.dependencies.db_sync.service }}"
              },
              {
                "name": "DEPENDENCY_JOBS",
                "value": "{{  include "joinListWithColon" .Values.dependencies.db_sync.jobs }}"
              },
              {
                "name": "COMMAND",
                "value": "echo done"
              }
            ]
          }
        ]'
    spec:
      restartPolicy: OnFailure
      containers:
        - name: keystone-db-sync
          image: {{ .Values.images.db_sync }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
          command:
            - bash
            - /tmp/db-sync.sh
          volumeMounts:
            - name: keystoneconf
              mountPath: /etc/keystone/keystone.conf
              subPath: keystone.conf
            - name: keystone-bin
              mountPath: /tmp/db-sync.sh
              subPath: db-sync.sh
          resources:
            requests:
              memory: {{ .Values.resources.keystone_db_sync.requests.memory | quote }}
              cpu: {{ .Values.resources.keystone_db_sync.requests.cpu | quote }}
            limits:
              memory: {{ .Values.resources.keystone_db_sync.limits.memory | quote }}
              cpu: {{ .Values.resources.keystone_db_sync.limits.cpu | quote }}
      volumes:
        - name: keystoneconf
          configMap:
            name: keystone-etc
        - name: keystone-bin
          configMap:
            name: keystone-bin
