{{- $envAll := . }}
{{- $ksAdminSecret := $envAll.Values.keystone.admin_secret | default "cinder-env-keystone-admin" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: cinder-ks-endpoints
spec:
  template:
    metadata:
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "init",
            "image": {{ .Values.images.dep_check | quote }},
            "imagePullPolicy": {{ .Values.images.pull_policy | quote }},
            "env": [
              {
                "name": "NAMESPACE",
                "value": "{{ .Release.Namespace }}"
              },
              {
                "name": "DEPENDENCY_SERVICE",
                "value": "{{ include "joinListWithColon" .Values.dependencies.ks_service.service }}"
              },
              {
                "name": "COMMAND",
                "value": "echo done"
              }
            ]
          }
        ]'
    spec:
      restartPolicy: OnFailure
      containers:
{{- range $key1, $osServiceType := tuple "volume" "volumev2" "volumev3" }}
{{- range $key2, $osServiceEndPoint := tuple "admin" "internal" "public" }}
        - name: {{ $osServiceType }}-ks-endpoints-{{ $osServiceEndPoint }}
          image: {{ $envAll.Values.images.ks_endpoints }}
          imagePullPolicy: {{ $envAll.Values.images.pull_policy }}
          command:
            - bash
            - /tmp/ks-endpoints.sh
          volumeMounts:
            - name: ks-endpoints-sh
              mountPath: /tmp/ks-endpoints.sh
              subPath: ks-endpoints.sh
              readOnly: true
          env:
{{- with $env := dict "ksUserSecret" $ksAdminSecret }}
{{- include "env_ks_openrc_tpl" $env | indent 12 }}
{{- end }}
            - name: OS_SVC_ENDPOINT
              value: {{ $osServiceEndPoint }}
            - name: OS_SERVICE_NAME
              value: {{ tuple $osServiceType $envAll | include "endpoint_name_lookup" }}
            - name: OS_SERVICE_TYPE
              value: {{ $osServiceType }}
            - name: OS_SERVICE_ENDPOINT
              value: {{ tuple $osServiceType $osServiceEndPoint "api" $envAll | include "endpoint_type_lookup_addr" }}
{{- end }}
{{- end }}
          resources:
            requests:
              memory: {{ .Values.resources.job_ks_endpoints.requests.memory | quote }}
              cpu: {{ .Values.resources.job_ks_endpoints.requests.cpu | quote }}
            limits:
              memory: {{ .Values.resources.job_ks_endpoints.limits.memory | quote }}
              cpu: {{ .Values.resources.job_ks_endpoints.limits.cpu | quote }}
      volumes:
        - name: ks-endpoints-sh
          configMap:
            name: cinder-bin
