apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: maas-rack
spec:
  template:
    metadata:
      labels:
        app: maas-rack-controller
    spec:
      nodeSelector:
        {{ .Values.labels.node_selector_key }}: {{ .Values.labels.node_selector_value }}
      hostNetwork: true
      containers:
      - name: maas-rack
        image: {{ .Values.images.maas_rack }}
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          requests:
            memory: {{ .Values.resources.maas_rack.requests.memory | quote }}
            cpu: {{ .Values.resources.maas_rack.requests.cpu | quote }}
          limits:
            memory: {{ .Values.resources.maas_rack.limits.memory | quote }}
            cpu: {{ .Values.resources.maas_rack.limits.cpu | quote }}
