apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nova-osapi
spec:
  replicas: {{ .Values.control_replicas }}
  revisionHistoryLimit: {{ .Values.upgrades.revision_history }}
  strategy:
    type: {{ .Values.upgrades.pod_replacement_strategy }}
    {{ if eq .Values.upgrades.pod_replacement_strategy "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.upgrades.rolling_update.max_unavailable }}
      maxSurge: {{ .Values.upgrades.rolling_update.max_surge }}
    {{ end }}  
  template:
    metadata:
      labels:
        app: nova-osapi
      annotations:
        configmap-bin-hash: {{ tuple "configmap-bin.yaml" . | include "hash" }}
        configmap-etc-hash: {{ tuple "configmap-etc.yaml" . | include "hash" }}        
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "init",
            "image": "{{ .Values.image.entrypoint }}",
            "imagePullPolicy": "{{ .Values.image.pull_policy }}",            
            "env": [
              {
                "name": "NAMESPACE",
                "value": "{{ .Release.Namespace }}"
              },
              {
                "name": "INTERFACE_NAME",
                "value": "eth0"
              },
              {
                "name": "DEPENDENCY_SERVICE",
                "value": "{{  include "joinListWithColon" .Values.dependencies.api.service }}"
              },
              {
                "name": "DEPENDENCY_JOBS",
                "value": "{{  include "joinListWithColon" .Values.dependencies.api.jobs }}"
              },
              {
                "name": "COMMAND",
                "value": "echo done"
              }              
            ]
          }
        ]'
    spec:
      nodeSelector:
        {{ .Values.labels.control_node_selector_key }}: {{ .Values.labels.control_node_selector_value }}
      containers:
        - name: nova-osapi
          image: {{ .Values.image.api }}
          command:
            - bash
            - /tmp/start-osapi.sh
          ports:
            - containerPort: {{ .Values.network.port.osapi }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.network.port.osapi }}
          volumeMounts:
            - name: novaconf
              mountPath: /etc/nova/nova.conf
              subPath: nova.conf
          volumeMounts:
            - name: startsh
              mountPath: /tmp/start-osapi.sh
              subPath: start-osapi.sh
          resources:
            requests:
              memory: {{ .Values.resources.nova_osapi.requests.memory | quote }}
              cpu: {{ .Values.resources.nova_osapi.requests.cpu | quote }}
            limits:
              memory: {{ .Values.resources.nova_osapi.limits.memory | quote }}
              cpu: {{ .Values.resources.nova_osapi.limits.cpu | quote }}
      volumes:
        - name: novaconf
          configMap:
            name: nova-etc
            items:
            - key: nova.conf
              path: nova.conf
        - name: startsh
          configMap:
            name: nova-bin
            items:
            - key: start-osapi.sh
              path: start-osapi.sh
