apiVersion: batch/v1
kind: Job
metadata:
  name: nova-init
spec:
  template:
    metadata:
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "init",
            "image": "{{ .Values.image.entrypoint }}",
            "imagePullPolicy": "{{ .Values.image.pull_policy }}",            
            "env": [
              {
                "name": "NAMESPACE",
                "value": "{{ .Release.Namespace }}"
              },
              {
                "name": "DEPENDENCY_SERVICE",
                "value": "{{  include "joinListWithColon" .Values.dependencies.init.service }}"
              },
              {
                "name": "DEPENDENCY_JOBS",
                "value": "{{  include "joinListWithColon" .Values.dependencies.init.jobs }}"
              },
              {
                "name": "COMMAND",
                "value": "echo done"
              }
            ]
          }
        ]'
    spec:
      restartPolicy: OnFailure
      containers:
        - name: nova-init
          image: {{ .Values.image.init }}
          imagePullPolicy: {{ .Values.image.pull_policy }}
          command:
            - bash
            - /tmp/init.sh
          volumeMounts:
            - name: nova-bin
              mountPath: /tmp/init.sh
              subPath: init.sh
          resources:
            requests:
              memory: {{ .Values.resources.nova_init.requests.memory | quote }}
              cpu: {{ .Values.resources.nova_init.requests.cpu | quote }}
            limits:
              memory: {{ .Values.resources.nova_init.limits.memory | quote }}
              cpu: {{ .Values.resources.nova_init.limits.cpu | quote }}
      volumes:
        - name: nova-bin
          configMap:
            name: nova-bin
