apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: ovs-agent
spec:
  template:
    metadata:
      labels:
        app: ovs-agent
      annotations:
        configmap-bin-hash: {{ tuple "configmap-bin.yaml" . | include "hash" }}
        configmap-etc-hash: {{ tuple "configmap-etc.yaml" . | include "hash" }}        
    spec:
      nodeSelector:
        {{ .Values.labels.ovs.node_selector_key }}: {{ .Values.labels.ovs.node_selector_value }}    
      securityContext:
        runAsUser: 0
      dnsPolicy: ClusterFirst
      hostNetwork: true
      containers:
        - name: ovs-agent
          image: {{ .Values.images.neutron_openvswitch_agent }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
          securityContext:
            privileged: true
          # ensures this container can can see a br-int
          # bridge before its marked as ready
          readinessProbe:
            exec:
              command:
                - bash
                - -c
                - 'ovs-vsctl list-br | grep -q br-int'
          env:
            - name: INTERFACE_NAME
              value: {{ .Values.network.interface.openvswitch | default .Values.network.interface.default }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: COMMAND
              value: "bash /tmp/neutron-openvswitch-agent.sh"
            - name: DEPENDENCY_JOBS
              value: "{{  include "joinListWithColon" .Values.dependencies.ovs_agent.jobs }}"
            - name: DEPENDENCY_SERVICE
              value: "{{  include "joinListWithColon" .Values.dependencies.ovs_agent.service }}"
          resources:
            requests:
              memory: {{ .Values.resources.neutron_ovs_agent.requests.memory | quote }}
              cpu: {{ .Values.resources.neutron_ovs_agent.requests.cpu | quote }}
            limits:
              memory: {{ .Values.resources.neutron_ovs_agent.limits.memory | quote }}
              cpu: {{ .Values.resources.neutron_ovs_agent.limits.cpu | quote }}
          volumeMounts:
            - name: neutronopenvswitchagentsh
              mountPath: /tmp/neutron-openvswitch-agent.sh
              subPath: neutron-openvswitch-agent.sh
            - name: neutronconf
              mountPath: /etc/neutron/neutron.conf
              subPath: neutron.conf
            - name: ml2confini
              mountPath: /etc/neutron/plugins/ml2/ml2-conf.ini
              subPath: ml2-conf.ini
            - name: libmodules
              mountPath: /lib/modules
              readOnly: true
            - name: run
              mountPath: /run
            - mountPath: /etc/resolv.conf
              name: resolvconf
              subPath: resolv.conf
      volumes:
        - name: varlibopenvswitch
          emptyDir: {}
        - name: neutronopenvswitchagentsh
          configMap:
            name: neutron-bin
        - name: neutronconf
          configMap:
            name: neutron-etc
        - name: ml2confini
          configMap:
            name: neutron-etc
        - name: resolvconf
          configMap:
            name: neutron-etc
        - name: libmodules
          hostPath:
            path: /lib/modules
        - name: run
          hostPath:
            path: /run                 
