# Default values for mariadb.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

# note that you need to update the gcomm member list
# below when changing this value
replicas: 3

# this flag allows a "leaner" version of this chart to be installed
# likely lacking any resiliency or persistence, but will help
# both laptop developers and cicd systems
#
# it will deploy a single instance of mariadb, use nodeDir
# for persistence and satisfy the mariadb-seed job with
# a busybox mock
#
# note enabling this flag takes precedence when enabled and
# will override certain things, like the replicas requested
development:
  enabled: false
  storage_path: /data/openstack-helm/mariadb

# this drives the service name, and statefulset name
service_name: mariadb

images:
  mariadb: quay.io/stackanetes/stackanetes-mariadb:newton

volume:
  class_path: volume.beta.kubernetes.io/storage-class
  class_name: general
  size: 20Gi

labels:
  node_selector_key: openstack-control-plane
  node_selector_value: enabled

network:
  port:
    wsrep: 4567 
    mariadb: 3306 
    ist: 4444
  dns:
    kubernetes_domain: cluster.local
  
database:
  root_password: password
  cluster_name: mariadb
  node_name: master

resources:
  mariadb_deployment:
    requests:
      memory: "124Mi"
      cpu: "200m"
    limits:
      memory: "1024Mi"
      cpu: "2000m"
  mariadb_init:
    requests:
      memory: "124Mi"
      cpu: "200m"
    limits:
      memory: "1024Mi"
      cpu: "2000m"
  
  
