# Default values for ironic.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
#
region: cluster
tld: local
debug: false

labels:
  control_node_selector_key: openstack-control-plane
  control_node_selector_value: enabled
  ironic_api_key: ironic-api
  ironic_api_value: enabled

replicas:
  api: 1
  conductor: 1
  inspector: 1
  pxe: 1
  
images:
  dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.1.0
  db_init: quay.io/stackanetes/stackanetes-kolla-toolbox:newton
  api: hub.docker.io/sapcc/ubuntu-source-ironic-api:v1
  conductor: hub.docker.io/sapcc/ubuntu-source-ironic-conductor:v1
  inspector: hub.docker.io/sapcc/ubuntu-source-ironic-inspector:v1
  pxe: hub.docker.io/sapcc/ubuntu-source-ironic-pxe:v1
  
  pull_policy: "IfNotPresent"

upgrades:
  revision_history: 5
  pod_replacement_strategy: RollingUpdate
  rolling_update:
    max_unavailable: 0
    max_surge: 3

ironic:    
  rpc_response_timeout: 120
  rpc_workers: 5
  
  inspector_port_internal: 5050
  
  service_user: ironic
  service_password: password
  
  api_endpoint_protocol_admin: http
  api_endpoint_protocol_internal: http
  api_endpoint_protocol_public: https
  
  api_port_admin: 6385
  api_port_internal: 6385
  api_port_public: 443
  
  pxe_port_public: 69
  pxe_endpoint_host_public: network0.yourdomain.com

database:
  db_user: "ironic"
  db_password: "password"
  db_name: "ironic"

keystone:
  ironic_user: "ironic"
  ironic_password: "password"
  
keystone:
  api_endpoint_protocol_internal: http
  api_port_internal: 5000
  api_endpoint_protocol_admin: http
  api_port_admin: 35357

memcached:
  port_public: 11211

glance:
  api_endpoint_protocol_internal: http
  api_port_internal: 9292

rabbitmq:
  default_user: openstack
  default_pass: password  
  address: rabbitmq
  admin_user: rabbitmq
  admin_password: password
  port: 5672

postgres:
  user: ironic
  password: password
  db_user: ironic
  db_password: password
  inspector_db_user: inspector
  inspector_db_password: password
  port_public: 5432

neutron:
  metadata_secret: "password"
  api_endpoint_protocol_internal: http
  api_port_internal: 9696

dependencies:
  api:
    jobs:
    - ironic-migration
    service:
    - postgres-ironic
    - rabbitmq
  conductor:
    service:
    - ironic-api
    - rabbitmq
  migration:
    service:
    - postgres-ironic
         
resources:
  enabled: false
  ironic_api:
    requests:
      memory: "124Mi"
      cpu: "100m"
    limits:
      memory: "1024Mi"
      cpu: "2000m"
  ironic_conductor:
    requests:
      memory: "124Mi"
      cpu: "100m"
    limits:
      memory: "1024Mi"
      cpu: "2000m"
  ironic_inspector:
    requests:
      memory: "124Mi"
      cpu: "100m"
    limits:
      memory: "1024Mi"
      cpu: "2000m"
  ironic_pxe:
    requests:
      memory: "124Mi"
      cpu: "100m"
    limits:
      memory: "1024Mi"
      cpu: "2000m"
  ironic_api_migration:
    requests:
      memory: "124Mi"
      cpu: "100m"
    limits:
      memory: "1024Mi"
      cpu: "2000m"
  ironic_inspector_migration:
    requests:
      memory: "124Mi"
      cpu: "100m"
    limits:
      memory: "1024Mi"
      cpu: "2000m"
