# Default values for keystone.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

replicas: 1

labels:
  node_selector_key: openstack-control-plane
  node_selector_value: enabled

images:
  db_sync: quay.io/stackanetes/stackanetes-glance-api:newton
  api: quay.io/stackanetes/stackanetes-glance-api:newton
  init: quay.io/stackanetes/stackanetes-kolla-toolbox:newton
  registry: quay.io/stackanetes/stackanetes-glance-registry:newton
  post: quay.io/stackanetes/stackanetes-kolla-toolbox:newton
  pull_policy: "IfNotPresent"

upgrades:
  revision_history: 3
  pod_replacement_strategy: RollingUpdate
  rolling_update:
    max_unavailable: 1
    max_surge: 3

keystone:
  auth_uri: "http://keystone-api:5000"
  auth_url: "http://keystone-api:35357"
  admin_user: "admin"
  admin_password: "password"
  admin_project_name: "admin"
  admin_region_name: "RegionOne"

  glance_user: "glance"
  glance_password: "password"
  glance_region_name: "RegionOne"

network:
  port:
    api: 9292
    registry: 9191
  ip_address: "0.0.0.0"

database:
  address: mariadb
  port: 3306
  root_user: root
  root_password: password
  glance_database_name: glance
  glance_password: password
  glance_user: glance

ceph:
  enabled: true
  monitors: []
  glance_user: "admin"
  glance_pool: "images"
  # a null value for the keyring will
  # attempt to use the key from
  # common/secrets/ceph-client-key
  glance_keyring: null

misc:
  workers: 8
  debug: false

dependencies:
  api:
    jobs:
    - glance-init
    - glance-db-sync
    - keystone-db-sync
    service:
    - keystone-api
    - mariadb
  registry:
    jobs:
    - glance-init
    - glance-db-sync
    - keystone-db-sync
    service:
    - keystone-api
    - mariadb
    - glance-api
  db_sync:
    jobs:
    - keystone-init
    - keystone-db-sync
    - glance-init
    - mariadb-seed
    service:
    - mariadb
  init:
    jobs:
    - mariadb-seed
    service:
    - mariadb
  post:
    jobs:
    - glance-init
    - glance-db-sync
    - keystone-db-sync
    - keystone-init
    - mariadb-seed
    service:
    - mariadb
    - keystone-api
    - glance-api
    - glance-registry

# typically overriden by environmental 
# values, but should include all endpoints
# required by this chart
endpoints:
  glance:
    hosts:
      default: glance-api
    type: image
    path: null
    scheme: 'http'
    port:
      api: 9292
      registry: 9191
  keystone:
    hosts:
      default: keystone-api
    path: /v3
    type: identity
    scheme: 'http'
    port:
        admin: 35357
        public: 5000

resources:
  glance_api:
    requests:
      memory: "124Mi"
      cpu: "200m"
    limits:
      memory: "1024Mi"
      cpu: "2000m"
  glance_db_sync:
    requests:
      memory: "124Mi"
      cpu: "200m"
    limits:
      memory: "1024Mi"
      cpu: "2000m"
  glance_init:
    requests:
      memory: "124Mi"
      cpu: "200m"
    limits:
      memory: "1024Mi"
      cpu: "2000m"
  glance_post:
    requests:
      memory: "124Mi"
      cpu: "200m"
    limits:
      memory: "1024Mi"
      cpu: "2000m"
  glance_registry:
    requests:
      memory: "124Mi"
      cpu: "200m"
    limits:
      memory: "1024Mi"
      cpu: "2000m"

