# Default values for maas.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

images:
  maas_region: quay.io/attcomdev/maas-region:2.1.2-1
  maas_rack: quay.io/attcomdev/maas-rack:2.1.2

labels:
  node_selector_key: openstack-control-plane
  node_selector_value: enabled

network:
  port:
    region_container: 80
    service_gui: 80
    service_gui_target: 80
    service_proxy: 8000
    service_proxy_target: 8000

service_name: maas-region-ui 

resources:
  maas_rack:
    requests:
      memory: "124Mi"
      cpu: "200m"
    limits:
      memory: "1024Mi"
      cpu: "2000m"
  maas_region:
    requests:
      memory: "124Mi"
      cpu: "200m"
    limits:
      memory: "1024Mi"
      cpu: "2000m"
